// Foto di parchi e animali da Wikimedia Commons, solo con licenza Creative Commons.
// Ogni foto va mostrata con autore e licenza (link alla pagina del file).
// Scelte a mano: per cambiarle usa una foto di Commons con licenza CC e aggiorna tutti i campi.
export const FOTO = {
  "pnalm": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Panoramica_del_Lago_di_Barrea_%28AQ%29.jpg/500px-Panoramica_del_Lago_di_Barrea_%28AQ%29.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Panoramica_del_Lago_di_Barrea_(AQ).jpg","autore":"Mario75Romano","licenza":"CC BY-SA 4.0","licenzaUrl":"https://creativecommons.org/licenses/by-sa/4.0"},
  "foreste-casentinesi": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6e/Luci_nella_faggeta.jpg/500px-Luci_nella_faggeta.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Luci_nella_faggeta.jpg","autore":"BocMau","licenza":"CC BY-SA 4.0","licenzaUrl":"https://creativecommons.org/licenses/by-sa/4.0"},
  "appennino-lucano": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/28/Lago_laudemio.jpg/500px-Lago_laudemio.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Lago_laudemio.jpg","autore":"Roberta Caramia","licenza":"CC BY-SA 4.0","licenzaUrl":"https://creativecommons.org/licenses/by-sa/4.0"},
  "pollino": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Parco_del_pollino-pini_loricati.jpg/500px-Parco_del_pollino-pini_loricati.jpg", "pagina": "https://commons.wikimedia.org/wiki/File:Parco_del_pollino-pini_loricati.jpg", "autore": "Rocco Sordetti", "licenza": "CC BY-SA 4.0", "licenzaUrl": "https://creativecommons.org/licenses/by-sa/4.0"},
  "gallipoli-cognato": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7f/Dolomiti_Lucane_%28Castelmezzano%29.jpg/500px-Dolomiti_Lucane_%28Castelmezzano%29.jpg", "pagina": "https://commons.wikimedia.org/wiki/File:Dolomiti_Lucane_(Castelmezzano).jpg", "autore": "Luigi Catalani", "licenza": "CC BY-SA 4.0", "licenzaUrl": "https://creativecommons.org/licenses/by-sa/4.0"},
  "majella": {"url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7f/La_Maiella_sopra_Caramanico_Terme_-_panoramio.jpg/500px-La_Maiella_sopra_Caramanico_Terme_-_panoramio.jpg", "pagina": "https://commons.wikimedia.org/wiki/File:La_Maiella_sopra_Caramanico_Terme_-_panoramio.jpg", "autore": "maury3001", "licenza": "CC BY 3.0", "licenzaUrl": "https://creativecommons.org/licenses/by/3.0"},
  "orso": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/07/Passeggiando_semplicemente.jpg/500px-Passeggiando_semplicemente.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Passeggiando_semplicemente.jpg","autore":"Mykola Pokalyuk","licenza":"CC BY-SA 4.0","licenzaUrl":"https://creativecommons.org/licenses/by-sa/4.0"},
  "lupo": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/C._l._italicus_in_MNP.jpg/500px-C._l._italicus_in_MNP.jpg","pagina":"https://commons.wikimedia.org/wiki/File:C._l._italicus_in_MNP.jpg","autore":"Eye Am Didier","licenza":"CC BY 2.0","licenzaUrl":"https://creativecommons.org/licenses/by/2.0"},
  "camoscio": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/06/Rupicapra_pyrenaica_ornata_94813569.jpg/500px-Rupicapra_pyrenaica_ornata_94813569.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Rupicapra_pyrenaica_ornata_94813569.jpg","autore":"Emanuele Santarelli","licenza":"CC BY-SA 4.0","licenzaUrl":"https://creativecommons.org/licenses/by-sa/4.0"},
  "cervo": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Red_deer_%28Cervus_elaphus%29_young_stag.jpg/500px-Red_deer_%28Cervus_elaphus%29_young_stag.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Red_deer_(Cervus_elaphus)_young_stag.jpg","autore":"Charles J. Sharp","licenza":"CC BY-SA 4.0","licenzaUrl":"https://creativecommons.org/licenses/by-sa/4.0"},
  "capriolo": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Capreolus_%28js%2911.jpg/500px-Capreolus_%28js%2911.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Capreolus_(js)11.jpg","autore":"Jerzystrzelecki","licenza":"CC BY 3.0","licenzaUrl":"https://creativecommons.org/licenses/by/3.0"},
  "daino": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/Fallow_deer_in_field.jpg/500px-Fallow_deer_in_field.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Fallow_deer_in_field.jpg","autore":"Johann-Nikolaus Andreae","licenza":"CC BY-SA 2.0","licenzaUrl":"https://creativecommons.org/licenses/by-sa/2.0"},
  "muflone": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e5/Mouflon_Corse.jpg/500px-Mouflon_Corse.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Mouflon_Corse.jpg","autore":"Clément Bardot","licenza":"CC BY-SA 4.0","licenzaUrl":"https://creativecommons.org/licenses/by-sa/4.0"},
  "cinghiale": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Wildschwein%2C_N%C3%A4he_Pulverstampftor.jpg/500px-Wildschwein%2C_N%C3%A4he_Pulverstampftor.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Wildschwein,_N%C3%A4he_Pulverstampftor.jpg","autore":"Valentin Panzirsch","licenza":"CC BY-SA 3.0 at","licenzaUrl":"https://creativecommons.org/licenses/by-sa/3.0/at/deed.en"},
  "volpe": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/Fox_at_the_British_Wildlife_Centre%2C_Newchapel%2C_Surrey_-_geograph.org.uk_-_2221750.jpg/500px-Fox_at_the_British_Wildlife_Centre%2C_Newchapel%2C_Surrey_-_geograph.org.uk_-_2221750.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Fox_at_the_British_Wildlife_Centre,_Newchapel,_Surrey_-_geograph.org.uk_-_2221750.jpg","autore":"Peter Trimming","licenza":"CC BY-SA 2.0","licenzaUrl":"https://creativecommons.org/licenses/by-sa/2.0"},
  "lontra": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/European_otter_01.jpg/500px-European_otter_01.jpg","pagina":"https://commons.wikimedia.org/wiki/File:European_otter_01.jpg","autore":"Alexander Leisser","licenza":"CC BY-SA 4.0","licenzaUrl":"https://creativecommons.org/licenses/by-sa/4.0"},
  "gatto_selvatico": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f4/Wildcat_at_British_Wildlife_Centre.jpg/500px-Wildcat_at_British_Wildlife_Centre.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Wildcat_at_British_Wildlife_Centre.jpg","autore":"Peter Trimming","licenza":"CC BY 2.0","licenzaUrl":"https://creativecommons.org/licenses/by/2.0"},
  "aquila_reale": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Aquila_chrysaetos_%28Linnaeus_1758%29.jpg/500px-Aquila_chrysaetos_%28Linnaeus_1758%29.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Aquila_chrysaetos_(Linnaeus_1758).jpg","autore":"Michael Gäbler","licenza":"CC BY 3.0","licenzaUrl":"https://creativecommons.org/licenses/by/3.0"},
  "gufo_reale": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/61/Hubro_%28Bubo_bubo%29.JPG/500px-Hubro_%28Bubo_bubo%29.JPG","pagina":"https://commons.wikimedia.org/wiki/File:Hubro_(Bubo_bubo).JPG","autore":"Marton Berntsen","licenza":"CC BY-SA 4.0","licenzaUrl":"https://creativecommons.org/licenses/by-sa/4.0"},
  "nibbio_reale": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/49/Milvus_milvus_Jura.jpg/500px-Milvus_milvus_Jura.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Milvus_milvus_Jura.jpg","autore":"Noel Reynolds","licenza":"CC BY 2.0","licenzaUrl":"https://creativecommons.org/licenses/by/2.0"},
  "cicogna_nera": {"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/ba/Ciconia_nigra_-Kruger_National_Park-8.jpg/500px-Ciconia_nigra_-Kruger_National_Park-8.jpg","pagina":"https://commons.wikimedia.org/wiki/File:Ciconia_nigra_-Kruger_National_Park-8.jpg","autore":"Chris Eason","licenza":"CC BY 2.0","licenzaUrl":"https://creativecommons.org/licenses/by/2.0"},
};

export const fotoDi = (chiave) => FOTO[chiave] ?? null;
